name: jQuery.asides
description: Transform Markdown footnotes into superpowered sidenotes.
markdown: kramdown
baseurl: /jquery.sidenotes

kramdown:
  use_coderay: true

  coderay:
    coderay_line_numbers: nil